### ISSUE TITLE
File transfer failure with large files using Warpinator between Linux Mint systems

### ISSUE THREAD

**Issue by munhyunsu** [linuxmint/warpinator#222]
### Distribution

Mint 22 -- Mint 22

### Package version

1.8.6 (Distro version)

### Frequency

Always

### Bug description

While attempting to transfer approximately 70 GB of files (two files of 30 GB and 40 GB) between two Linux Mint 22 hosts using Warpinator, the transfer failed with a "Finished, with error" message.

After the transfer failure, the two hosts are unable to detect each other. Restarting Warpinator on both hosts allows them to reconnect, but the transfer fails again when retried. Out of about 10 attempts, only 1–2 succeed. This issue seems to persist consistently with large file transfers.

### Steps to reproduce

1. [Sender/Receiver] Launch Warpinator on both systems.
2. [Sender] Add large files (approximately 70 GB in total, consisting of two files: 30 GB and 40 GB) to the transfer queue using drag-and-drop.
3. [Receiver] Accept the transfer request by clicking the "Accept" button in Warpinator.
4. The file transfer fails with a "Finished, with error" message.

### Expected behavior

Transfer success!

### Additional information

Sender log: [sender_log.txt](https://github.com/user-attachments/files/18138485/sender_log.txt)

Receiver log: [receiver_log.txt](https://github.com/user-attachments/files/18138487/receiver_log.txt)

**Comment by JeffCarr** [comment]
I have this exact same issue.  In my case the receiving computer could connect to the sender, but the sender reported the receiver as offline.  Restarting the sender worked, but the file transfer could not be successfully continued.

**Comment by tuxayo** [comment]
I have similar symptoms but I have this error on the receiver that isn't is OP's log.
The sender still sees the receiver connected with the transfert "in progress" but frozen. And the received see the sender as offline.

```
2025-07-06 05:29:27,310::warpinator::DEBUG: NewThreadExecutor: Poking the factory. -- util.py (line 102)
2025-07-06 05:29:27,310::warpinator::DEBUG: NewThreadExecutor: Starting thread for op: op-thread-4755647637, thread count UP: 1 -- util.py (line 112)
2025-07-06 05:29:27,310::warpinator::DEBUG: Remote RPC: Calling StopTransfer on 'some-laptop' -- remote.py (line 535)
2025-07-06 05:29:27,310::warpinator::DEBUG: Remote: stop transfer initiated by receiver -- remote.py (line 556)
Exception in thread op-thread-4755647637:
2025-07-06 05:29:27,311::warpinator::DEBUG: NewThreadExecutor: Waiting on an op -- util.py (line 70)
Traceback (most recent call last):
  File "/usr/lib/python3.13/threading.py", line 1043, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "/usr/lib/python3.13/threading.py", line 994, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/warpinator/util.py", line 122, in _transfer_thread_func
    opinfo[0](*opinfo[1], **opinfo[2])
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/warpinator/remote.py", line 570, in stop_transfer_op
    self.stub.StopTransfer(warp_pb2.StopInfo(info=opinfo, error=op.error_msg != ""))
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/grpc/_channel.py", line 1178, in __call__
    ) = self._blocking(
        ~~~~~~~~~~~~~~^
        request, timeout, metadata, credentials, wait_for_ready, compression
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib/python3.13/site-packages/grpc/_channel.py", line 1146, in _blocking
    call = self._channel.segregated_call(
        cygrpc.PropagationConstants.GRPC_PROPAGATE_DEFAULTS,
    ...<12 lines>...
        self._registered_call_handle,
    )
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 547, in grpc._cython.cygrpc.Channel.segregated_call
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 403, in grpc._cython.cygrpc._segregated_call
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 407, in grpc._cython.cygrpc._segregated_call
ValueError: Cannot invoke RPC on closed channel!
2025-07-06 05:29:27,316::warpinator::DEBUG: UI: No more active transfers, uninhibiting suspend/logout -- warpinator.py (line 1601)
2025-07-06 05:29:27,317::warpinator::DEBUG: FreeSpaceMonitor pause -- util.py (line 556)
2025-07-06 05:29:27,327::warpinator::DEBUG: FreeSpaceMonitor pause -- util.py (line 556)
2025-07-06 05:29:27,501::warpinator::DEBUG: Remote: other-pc-hostname is now OFFLINE **** -- remote.py (line 313)
```

And the sender's log look normal until saying:
transfert finished  -- server.py line 628
It doesn't match the UI.
